# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flocations.proto\"a\n\x10LocationsMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x15\n\rcreation_time\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x11\n\tlongitude\x18\x04 \x01(\t2A\n\x0fLocationService\x12.\n\x06\x43reate\x12\x11.LocationsMessage\x1a\x11.LocationsMessageb\x06proto3')



_LOCATIONSMESSAGE = DESCRIPTOR.message_types_by_name['LocationsMessage']
LocationsMessage = _reflection.GeneratedProtocolMessageType('LocationsMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONSMESSAGE,
  '__module__' : 'locations_pb2'
  # @@protoc_insertion_point(class_scope:LocationsMessage)
  })
_sym_db.RegisterMessage(LocationsMessage)

_LOCATIONSERVICE = DESCRIPTOR.services_by_name['LocationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONSMESSAGE._serialized_start=19
  _LOCATIONSMESSAGE._serialized_end=116
  _LOCATIONSERVICE._serialized_start=118
  _LOCATIONSERVICE._serialized_end=183
# @@protoc_insertion_point(module_scope)
