# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: persons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpersons.proto\"Y\n\x0ePersonsMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t2;\n\rPersonService\x12*\n\x06\x43reate\x12\x0f.PersonsMessage\x1a\x0f.PersonsMessageb\x06proto3')



_PERSONSMESSAGE = DESCRIPTOR.message_types_by_name['PersonsMessage']
PersonsMessage = _reflection.GeneratedProtocolMessageType('PersonsMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONSMESSAGE,
  '__module__' : 'persons_pb2'
  # @@protoc_insertion_point(class_scope:PersonsMessage)
  })
_sym_db.RegisterMessage(PersonsMessage)

_PERSONSERVICE = DESCRIPTOR.services_by_name['PersonService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSONSMESSAGE._serialized_start=17
  _PERSONSMESSAGE._serialized_end=106
  _PERSONSERVICE._serialized_start=108
  _PERSONSERVICE._serialized_end=167
# @@protoc_insertion_point(module_scope)
