apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-persons-locations-consumer
  name: udaconnect-persons-locations-consumer
spec:
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9093
      nodePort: 30040
  selector:
    service: udaconnect-persons-locations-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-persons-locations-consumer
  name: udaconnect-persons-locations-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-persons-locations-consumer
  template:
    metadata:
      labels:
        service: udaconnect-persons-locations-consumer
    spec:
      containers:
      - image: xeusteerapat/udaconnect-persons-locations-consumer:latest
        name: udaconnect-persons-locations-consumer
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "128m"
        env: # refer to config.py file
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        restartPolicy: Always