apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 30020
  selector:
    service: udaconnect-location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-producer
  template:
    metadata:
      labels:
        service: udaconnect-location-producer
    spec:
      containers:
      - image: xeusteerapat/udaconnect-location-producer:latest
        name: udaconnect-location-producer
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "128m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
        env: # refer to config.py file
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
          