apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-grpc-server
  name: udaconnect-grpc-server
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30030
  selector:
    service: udaconnect-grpc-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  lebels:
    service: udaconnect-grpc-server
  name: udaconnect-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-grpc-server
  template:
    metadata:
      labels:
        service: udaconnect-grpc-server
    spec:
      containers:
      - image: xeusteerapat/udaconnect-grpc-server:latest
        name: udaconnect-grpc-server
        imagePullPolicy: Always
        resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 410m
              memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
        env: # refer to config.py file
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        restartPolicy: Always
        