name: UdaConnect - Package with Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push Persons API Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./modules/persons-api
          file: ./modules/persons-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-person-api:latest
      - name: Build and push Location producer Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./modules/locations-producer
          file: ./modules/locations-producer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-locations-producer:latest
      - name: Build and push Location consumer Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./modules/locations-consumer
          file: ./modules/locations-consumer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-locations-consumer:latest
      - name: Build and push Connections API Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./modules/connections-api
          file: ./modules/connections-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-connections-api:latest
      - name: Build and push UdaConnect Frontend Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./modules/frontend
          file: ./modules/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-frontend:latest