name: UdaConnect - Package with Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push gRPC server Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: ./modules/grpc_server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-grpc-server:latest
      - name: Build and push location producer Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: ./modules/locations-producer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-location-producer:latest
      - name: Build and push persons connection API Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: ./modules/persons-connection/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-person-connections-api:latest
      - name: Build and push persons locations consumer Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: ./modules/persons-locations-consumer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: xeusteerapat/udaconnect-persons-locations-consumer:latest